---
title: "In-class_Ex03"
---

Loading packages that are needed for this exercise

```{r}
pacman::p_load(sf, raster, tmap, tidyverse, spatstat)
```

Importing datasets that will be used for this exercise

```{r}
mpsz_sf <- st_read(dsn = "/Users/chuangjinlei/Desktop/JinLei13/IS415-GAA/In-class_Ex/In-class_Ex03/data/geospatial", layer = "MP14_SUBZONE_WEB_PL") |> st_set_crs(3414)
childcare_sf <- st_read("/Users/chuangjinlei/Desktop/JinLei13/IS415-GAA/In-class_Ex/In-class_Ex03/data/geospatial/ChildCareServices.geojson") |> st_transform(crs = 3414)

```

Converting to PPP format

```{r}
childcare_ppp <- as.ppp(childcare_sf)

```

Deriving coastal outline

```{r}
sg_sf <- mpsz_sf |> st_union()
plot(sg_sf)
```

Checking for duplication

```{r}
any(duplicated(childcare_ppp))
```

Creating owin object

```{r}
sg_owin <- as.owin(sg_sf)
summary(sg_owin)
```

Combining both data

```{r}
childcareSG_ppp <- childcare_ppp[sg_owin]
```

Extracting study planning area

```{r}
pg <- filter(mpsz_sf, PLN_AREA_N == "PUNGGOL")
tm <- mpsz_sf |> filter(PLN_AREA_N == "TAMPINES")
ck <- mpsz_sf |> filter(PLN_AREA_N == "CHOA CHU KANG")
jw <- mpsz_sf |> filter(PLN_AREA_N == "JURONG WEST")
```

Plotting of study area

```{r}
par(mfrow = c(2,2))
plot(pg$geometry, main = "Ponggol")
plot(tm$geometry, main = "Tampines")
plot(ck$geometry, main = "Tampines")
plot(jw$geometry, main = "Jurong East")
```
