<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Chuang Jin Lei">
<meta name="dcterms.date" content="2024-03-11">

<title>IS415-GAA - Take-home Exercise 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Hands on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html" rel="" target="">
 <span class="dropdown-text">Hands on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html" rel="" target="">
 <span class="dropdown-text">Hands on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">In class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex02/In-class_Ex02.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03-NKDE.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/In-class_Ex05.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Take-home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html" rel="" target="">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html" rel="" target="">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">1 Overview</a>
  <ul class="collapse">
  <li><a href="#setting-the-scene" id="toc-setting-the-scene" class="nav-link" data-scroll-target="#setting-the-scene">1.1 Setting the scene</a></li>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives">1.2 Objectives</a></li>
  <li><a href="#the-tasks" id="toc-the-tasks" class="nav-link" data-scroll-target="#the-tasks">1.3 The Tasks</a></li>
  </ul></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">2 Setup</a>
  <ul class="collapse">
  <li><a href="#packages-that-will-be-used-for-this-exercise" id="toc-packages-that-will-be-used-for-this-exercise" class="nav-link" data-scroll-target="#packages-that-will-be-used-for-this-exercise">2.1 Packages that will be used for this exercise</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">3 Data</a>
  <ul class="collapse">
  <li><a href="#description-of-the-data" id="toc-description-of-the-data" class="nav-link" data-scroll-target="#description-of-the-data">3.1 Description of the Data</a></li>
  <li><a href="#uploading-the-data-into-the-environment" id="toc-uploading-the-data-into-the-environment" class="nav-link" data-scroll-target="#uploading-the-data-into-the-environment">3.2 Uploading the data into the environment</a></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling">3.3 Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#obtaining-study-area-in-sf-polygon-feature" id="toc-obtaining-study-area-in-sf-polygon-feature" class="nav-link" data-scroll-target="#obtaining-study-area-in-sf-polygon-feature">3.3.1 Obtaining study area in sf polygon feature</a></li>
  <li><a href="#data-wrangling-on-dengue-dataframe" id="toc-data-wrangling-on-dengue-dataframe" class="nav-link" data-scroll-target="#data-wrangling-on-dengue-dataframe">3.3.2 Data Wrangling on Dengue dataframe</a></li>
  </ul></li>
  <li><a href="#data-processing" id="toc-data-processing" class="nav-link" data-scroll-target="#data-processing">3.4 Data processing</a>
  <ul class="collapse">
  <li><a href="#converting-denguewk-aspatial-data-into-geospatial-data" id="toc-converting-denguewk-aspatial-data-into-geospatial-data" class="nav-link" data-scroll-target="#converting-denguewk-aspatial-data-into-geospatial-data">3.4.1 Converting denguewk aspatial data into geospatial data</a></li>
  <li><a href="#obtaining-boundary-of-the-study-area" id="toc-obtaining-boundary-of-the-study-area" class="nav-link" data-scroll-target="#obtaining-boundary-of-the-study-area">3.4.2 Obtaining boundary of the study area</a></li>
  <li><a href="#obtaining-dengue-cases-that-are-in-the-study-area" id="toc-obtaining-dengue-cases-that-are-in-the-study-area" class="nav-link" data-scroll-target="#obtaining-dengue-cases-that-are-in-the-study-area">3.4.3 Obtaining dengue cases that are in the study area</a></li>
  <li><a href="#deriving-a-dengue-fever-layer-in-spacetime-s3class-of-sfdep" id="toc-deriving-a-dengue-fever-layer-in-spacetime-s3class-of-sfdep" class="nav-link" data-scroll-target="#deriving-a-dengue-fever-layer-in-spacetime-s3class-of-sfdep">3.4.4 Deriving a dengue fever layer in spacetime s3class of sfdep</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#global-spatial-autocorrelation-analysis" id="toc-global-spatial-autocorrelation-analysis" class="nav-link" data-scroll-target="#global-spatial-autocorrelation-analysis">4 Global Spatial Autocorrelation Analysis</a>
  <ul class="collapse">
  <li><a href="#deriving-the-spatial-weights" id="toc-deriving-the-spatial-weights" class="nav-link" data-scroll-target="#deriving-the-spatial-weights">4.1 Deriving the spatial weights</a></li>
  <li><a href="#computing-global-morans-i" id="toc-computing-global-morans-i" class="nav-link" data-scroll-target="#computing-global-morans-i">4.2 Computing Global Moran’s I</a></li>
  <li><a href="#performing-global-morans-i-test" id="toc-performing-global-morans-i-test" class="nav-link" data-scroll-target="#performing-global-morans-i-test">4.3 Performing Global Moran’s I test</a></li>
  <li><a href="#performing-global-morans-i-permutation-test" id="toc-performing-global-morans-i-permutation-test" class="nav-link" data-scroll-target="#performing-global-morans-i-permutation-test">4.4 Performing Global Moran’s I permutation test</a></li>
  </ul></li>
  <li><a href="#local-spatial-autocorrelation-analysis" id="toc-local-spatial-autocorrelation-analysis" class="nav-link" data-scroll-target="#local-spatial-autocorrelation-analysis">5 Local Spatial Autocorrelation Analysis</a>
  <ul class="collapse">
  <li><a href="#computing-local-morans-i" id="toc-computing-local-morans-i" class="nav-link" data-scroll-target="#computing-local-morans-i">5.1 Computing Local Moran’s I</a></li>
  <li><a href="#joining-data" id="toc-joining-data" class="nav-link" data-scroll-target="#joining-data">5.2 Joining data</a></li>
  <li><a href="#visualising-local-morans-i" id="toc-visualising-local-morans-i" class="nav-link" data-scroll-target="#visualising-local-morans-i">5.3 Visualising Local Moran’s I</a></li>
  <li><a href="#visualising-p-value-of-local-morans-i-statistic" id="toc-visualising-p-value-of-local-morans-i-statistic" class="nav-link" data-scroll-target="#visualising-p-value-of-local-morans-i-statistic">5.4 Visualising p-value of Local Moran’s I statistic</a></li>
  <li><a href="#visualising-local-morans-i-and-p-value" id="toc-visualising-local-morans-i-and-p-value" class="nav-link" data-scroll-target="#visualising-local-morans-i-and-p-value">5.5 Visualising local Moran’s I and p-value</a></li>
  <li><a href="#visualising-lisa-map" id="toc-visualising-lisa-map" class="nav-link" data-scroll-target="#visualising-lisa-map">5.6 Visualising LISA Map</a></li>
  </ul></li>
  <li><a href="#emerging-hotspot-analysis" id="toc-emerging-hotspot-analysis" class="nav-link" data-scroll-target="#emerging-hotspot-analysis">6 Emerging Hotspot analysis</a>
  <ul class="collapse">
  <li><a href="#computing-ehsa" id="toc-computing-ehsa" class="nav-link" data-scroll-target="#computing-ehsa">6.1 Computing EHSA</a></li>
  <li><a href="#visualising-the-distribution-of-ehsa-classes" id="toc-visualising-the-distribution-of-ehsa-classes" class="nav-link" data-scroll-target="#visualising-the-distribution-of-ehsa-classes">6.2 Visualising the distribution of EHSA classes</a></li>
  <li><a href="#visualising-ehsa" id="toc-visualising-ehsa" class="nav-link" data-scroll-target="#visualising-ehsa">6.3 Visualising EHSA</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">7 Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Chuang Jin Lei </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 11, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="overview" class="level1">
<h1>1 Overview</h1>
<section id="setting-the-scene" class="level2">
<h2 class="anchored" data-anchor-id="setting-the-scene">1.1 Setting the scene</h2>
<p><a href="https://www.cdc.gov/dengue/resources/denguedhf-information-for-health-care-practitioners_2009.pdf">Dengue Hemorrhagic Fever</a>&nbsp;(in short dengue fever) is one of the most widespread mosquito-borne diseases in the most tropical and subtropical regions. It is an acute disease caused by dengue virus infection which is transmitted by female Aedes aegypti and Aedes albopictus mosquitoes. In 2015, Taiwan had recorded the most severe dengue fever outbreak with more than 43,000 dengue cases and 228 deaths. Since then, the annual reported dengue fever cases were maintained at the level of not more than 200 cases. However, in 2023, Taiwan recorded 26703 dengue fever cases. Figure below reveals that more than 25,000 cases were reported at Tainan City.</p>
<p><img src="https://is415-ay2023-24t2.netlify.app/img/df1.jpg" class="img-fluid">Figure 2 and 3 below reveal that more than 80% of the reported dengue fever cases occurred in the month August-November 2023 and epidemiology week 31-50.</p>
<p><img src="https://is415-ay2023-24t2.netlify.app/img/df2.jpg" class="img-fluid"></p>
<p><img src="https://is415-ay2023-24t2.netlify.app/img/df3.jpg" class="img-fluid"></p>
</section>
<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives">1.2 Objectives</h2>
<p>As a curious geospatial analytics green horn, I am interested to discover:</p>
<ul>
<li><p>if the distribution of dengue fever outbreak at Tainan City, Taiwan are independent from space and space and time.</p></li>
<li><p>If the outbreak is indeed spatial and spatio-temporal dependent, then, you would like to detect where are the clusters and outliers, and the emerging hot spot/cold spot areas.</p></li>
</ul>
</section>
<section id="the-tasks" class="level2">
<h2 class="anchored" data-anchor-id="the-tasks">1.3 The Tasks</h2>
<p>The specific tasks of this take-home exercise are as follows:</p>
<ul>
<li><p>Using appropriate function of&nbsp;<strong>sf</strong>&nbsp;and&nbsp;<strong>tidyverse</strong>, preparing the following geospatial data layer:</p>
<ul>
<li><p>a study area layer in sf polygon features. It must be at village level and confined to the D01, D02, D04, D06, D07, D08, D32 and D39 counties of Tainan City, Taiwan.</p></li>
<li><p>a dengue fever layer within the study area in sf point features. The dengue fever cases should be confined to epidemiology week 31-50, 2023.</p></li>
<li><p>a derived dengue fever layer in&nbsp;<a href="https://sfdep.josiahparry.com/articles/spacetime-s3">spacetime s3 class of sfdep</a>. It should contain, among many other useful information, a data field showing number of dengue fever cases by village and by epidemiology week.</p></li>
</ul></li>
<li><p>Using the extracted data, perform global spatial autocorrelation analysis by using&nbsp;<a href="https://is415-gaa-tskam.netlify.app/in-class_ex/in-class_ex05/in-class_ex05-glsa">sfdep methods</a>.</p></li>
<li><p>Using the extracted data, perform local spatial autocorrelation analysis by using&nbsp;<a href="https://r4gdsa.netlify.app/chap10.html">sfdep methods</a>.</p></li>
<li><p>Using the extracted data, perform emerging hotspot analysis by using&nbsp;<a href="https://is415-gaa-tskam.netlify.app/in-class_ex/in-class_ex05/in-class_ex05-ehsa">sfdep methods</a>.</p></li>
<li><p>Describe the spatial patterns revealed by the analysis above.</p></li>
</ul>
</section>
</section>
<section id="setup" class="level1">
<h1>2 Setup</h1>
<section id="packages-that-will-be-used-for-this-exercise" class="level2">
<h2 class="anchored" data-anchor-id="packages-that-will-be-used-for-this-exercise">2.1 Packages that will be used for this exercise</h2>
<ol type="1">
<li><p>tidyverse: It is for performing data science tasks such as importing, wrangling and visualising data Tidyverse consist of a family of R packages that includes:</p>
<p>readr: It is for importing csv data.</p>
<p>readxl: It is for importing excel worksheets.</p>
<p>tidyr: It is for manipulating data.</p>
<p>dplyr: It is for data wrangling.</p>
<p>ggplot2: It is for visualising data.</p></li>
<li><p>sf: It is for importing, managing, and processing geospatial data</p></li>
<li><p>tmap: It is for plotting choropleth maps.</p></li>
<li><p>sfdep: It is used for deriving a layer of spacetime s3 class, geometry neighbors, weights and local indicators of spatial association (LISAs).</p></li>
<li><p>lubridate: It provides functions to work with date-times and time-spans.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span> <span class="fu">p_load</span>(tidyverse, sf, tmap, sfdep, lubridate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="data" class="level1">
<h1>3 Data</h1>
<section id="description-of-the-data" class="level2">
<h2 class="anchored" data-anchor-id="description-of-the-data">3.1 Description of the Data</h2>
<ul>
<li><p>TAIWAN_VILLAGE_2020, a geospatial data of village boundary of Taiwan. It is in ESRI shapefile format. The data is in Taiwan Geographic Coordinate System. (Source:&nbsp;<a href="https://data.gov.tw/en/datasets/130549">Historical map data of the village boundary: TWD97 longitude and latitude</a>)</p></li>
<li><p>Dengue_Daily.csv, an aspatial data of reported dengue cases in Taiwan since 1998. (Source:&nbsp;<a href="https://data.cdc.gov.tw/en/dataset/dengue-daily-determined-cases-1998">Dengue Daily Confirmed Cases Since 1998</a>. Below are selected fields that are useful for this study:</p>
<ul>
<li><p>發病日: Onset date</p></li>
<li><p>最小統計區中心點X: x-coordinate</p></li>
<li><p>最小統計區中心點Y: y-coordinate</p></li>
</ul></li>
</ul>
</section>
<section id="uploading-the-data-into-the-environment" class="level2">
<h2 class="anchored" data-anchor-id="uploading-the-data-into-the-environment">3.2 Uploading the data into the environment</h2>
<ul>
<li><p>st_read() function from sf package is used to import the shapefile file</p></li>
<li><p>read.csv() function from readr package is used to import the csv file</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>tn <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/geospatial"</span>, <span class="at">layer =</span> <span class="st">"TAINAN_VILLAGE"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `TAINAN_VILLAGE' from data source 
  `/Users/chuangjinlei/Desktop/JinLei13/IS415-GAA/Take-home_Ex/Take-home_Ex02/data/geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 649 features and 10 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 120.0269 ymin: 22.88751 xmax: 120.6563 ymax: 23.41374
Geodetic CRS:  TWD97</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>dengue <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/aspatial/Dengue_Daily.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Checking the contents of the dataset before data manipulation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 10 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 120.053 ymin: 22.93251 xmax: 120.2905 ymax: 23.16919
Geodetic CRS:  TWD97
     VILLCODE COUNTYNAME TOWNNAME VILLNAME        VILLENG COUNTYID COUNTYCODE
1 67000280002     臺南市   歸仁區   六甲里    Liujia Vil.        D      67000
2 67000350032     臺南市   安南區   青草里   Qingcao Vil.        D      67000
3 67000150009     臺南市   七股區   溪南里     Xinan Vil.        D      67000
4 67000150010     臺南市   七股區   七股里      Qigu Vil.        D      67000
5 67000150008     臺南市   七股區   龍山里  Longshan Vil.        D      67000
6 67000150017     臺南市   七股區   中寮里 Zhongliao Vil.        D      67000
  TOWNID TOWNCODE NOTE                       geometry
1    D33 67000280 &lt;NA&gt; POLYGON ((120.2725 22.95868...
2    D06 67000350 &lt;NA&gt; POLYGON ((120.1176 23.08387...
3    D22 67000150 &lt;NA&gt; POLYGON ((120.121 23.1355, ...
4    D22 67000150 &lt;NA&gt; POLYGON ((120.1312 23.1371,...
5    D22 67000150 &lt;NA&gt; POLYGON ((120.0845 23.13503...
6    D22 67000150 &lt;NA&gt; POLYGON ((120.126 23.16917,...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dengue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      發病日 個案研判日     通報日 性別 年齡層 居住縣市 居住鄉鎮 居住村里
1 1998/01/02       None 1998/01/07   男  40-44   屏東縣   屏東市     None
2 1998/01/03       None 1998/01/14   男  30-34   屏東縣   東港鎮     None
3 1998/01/13       None 1998/02/18   男  55-59   宜蘭縣   宜蘭市     None
4 1998/01/15       None 1998/01/23   男  35-39   高雄市   苓雅區     None
5 1998/01/20       None 1998/02/04   男  55-59   宜蘭縣   五結鄉     None
6 1998/01/22       None 1998/02/19   男  20-24   桃園市   蘆竹區     None
     最小統計區 最小統計區中心點X 最小統計區中心點Y   一級統計區 二級統計區
1 A1320-0136-00     120.505898941      22.464206650 A1320-04-008   A1320-04
2 A1303-0150-00     120.453657460      22.466338948 A1303-09-007   A1303-09
3 A0201-0449-00     121.751433765      24.749214667 A0201-23-006   A0201-23
4 A6408-0153-00     120.338158907      22.630316700 A6408-10-010   A6408-10
5 A0209-0232-00     121.798235373      24.684507639 A0209-10-005   A0209-10
6          None              None              None         None       None
  感染縣市 感染鄉鎮 感染村里 是否境外移入 感染國家 確定病例數 居住村里代碼
1     None     None     None           否     None          1         None
2     None     None     None           是     None          1         None
3     None     None     None           是     None          1         None
4     None     None     None           否     None          1         None
5     None     None     None           否     None          1         None
6     None     None     None           是     None          1         None
  感染村里代碼 血清型 內政部居住縣市代碼 內政部居住鄉鎮代碼 內政部感染縣市代碼
1         None   None              10013            1001301               None
2         None 第二型              10013            1001303               None
3         None   None              10002            1000201               None
4         None   None                 64            6400800               None
5         None   None              10002            1000209               None
6         None   None                 68            6800500               None
  內政部感染鄉鎮代碼
1               None
2               None
3               None
4               None
5               None
6               None</code></pre>
</div>
</div>
</section>
<section id="data-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="data-wrangling">3.3 Data Wrangling</h2>
<section id="obtaining-study-area-in-sf-polygon-feature" class="level3">
<h3 class="anchored" data-anchor-id="obtaining-study-area-in-sf-polygon-feature">3.3.1 Obtaining study area in sf polygon feature</h3>
<ul>
<li>filter() function from dplyr package is used to confine the study area layer in sf polygon features to D01, D02, D04, D06, D07, D08, D32 and D39 counties of Tainan City, Taiwan.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Tainan <span class="ot">&lt;-</span>  tn <span class="sc">|&gt;</span> <span class="fu">filter</span>(TOWNID <span class="sc">==</span> <span class="st">"D01"</span> <span class="sc">|</span> TOWNID <span class="sc">==</span> <span class="st">"D02"</span> <span class="sc">|</span> TOWNID <span class="sc">==</span> <span class="st">"D04"</span><span class="sc">|</span> TOWNID <span class="sc">==</span>   <span class="st">"D06"</span> <span class="sc">|</span> TOWNID <span class="sc">==</span> <span class="st">"D07"</span> <span class="sc">|</span> TOWNID <span class="sc">==</span> <span class="st">"D08"</span> <span class="sc">|</span> TOWNID <span class="sc">==</span> <span class="st">"D32"</span> <span class="sc">|</span> TOWNID <span class="sc">==</span> <span class="st">"D39"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Checking Coordinate reference system of Tainan geospatial object</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(Tainan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: TWD97 
  wkt:
GEOGCRS["TWD97",
    DATUM["Taiwan Datum 1997",
        ELLIPSOID["GRS 1980",6378137,298.257222101,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Horizontal component of 3D system."],
        AREA["Taiwan, Republic of China - onshore and offshore - Taiwan Island, Penghu (Pescadores) Islands."],
        BBOX[17.36,114.32,26.96,123.61]],
    ID["EPSG",3824]]</code></pre>
</div>
</div>
<ul>
<li><p>The units are in decimal degree which corresponds to a Geographic Coordinate system</p></li>
<li><p>Coordinate reference system is TWD97</p></li>
<li><p>EPSG code is 3824</p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Screenshot 2024-03-03 at 4.47.19 AM.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Information on TWD97 Source: <a href="https://epsg.io/3824" class="uri">https://epsg.io/3824</a></figcaption>
</figure>
</div>
<p>Upon checking information on TWD97, the unit of measurements and EPSG code matches.</p>
</section>
<section id="data-wrangling-on-dengue-dataframe" class="level3">
<h3 class="anchored" data-anchor-id="data-wrangling-on-dengue-dataframe">3.3.2 Data Wrangling on Dengue dataframe</h3>
<ul>
<li><p>as_date() function from the lubridate package is used to convert the attribute from character format into the correct date format</p></li>
<li><p>filter() function from dplyr package is then being used to confine dengue fever cases to year 2023</p></li>
<li><p>The epidemiologyweek attribute is calculated using week() function from the lubridate package to count the week of the year</p></li>
<li><p>filter() function from dplyr package is then being used to confine dengue fever cases to epidemiology week 31 to 50</p></li>
<li><p>as.numeric() function is used to the x-coordinate and y-coordinate attribute from character object into the appropriate numerical object</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>dengue <span class="ot">&lt;-</span> dengue <span class="sc">|&gt;</span> <span class="fu">mutate</span>(發病日 <span class="ot">=</span> <span class="fu">as_date</span>(發病日))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>dengue2023 <span class="ot">&lt;-</span> dengue <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="fu">year</span>(發病日) <span class="sc">==</span> <span class="dv">2023</span> )</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>dengue2023 <span class="ot">&lt;-</span> dengue2023 <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="st">"epidemiologyweek"</span> <span class="ot">=</span> <span class="fu">week</span>(發病日))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>denguewk <span class="ot">&lt;-</span> dengue2023 <span class="sc">|&gt;</span> <span class="fu">filter</span>(epidemiologyweek <span class="sc">==</span> <span class="dv">31</span><span class="sc">:</span><span class="dv">50</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>denguewk <span class="ot">&lt;-</span> denguewk <span class="sc">|&gt;</span> <span class="fu">mutate</span>(最小統計區中心點<span class="at">X =</span> <span class="fu">as.numeric</span>(最小統計區中心點X), 最小統計區中心點<span class="at">Y =</span> <span class="fu">as.numeric</span>(最小統計區中心點Y) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="data-processing" class="level2">
<h2 class="anchored" data-anchor-id="data-processing">3.4 Data processing</h2>
<section id="converting-denguewk-aspatial-data-into-geospatial-data" class="level3">
<h3 class="anchored" data-anchor-id="converting-denguewk-aspatial-data-into-geospatial-data">3.4.1 Converting denguewk aspatial data into geospatial data</h3>
<ul>
<li><p>Since the x and y coordinate is in decimal degree, it is highly likely to be in geographic coordinate system.</p></li>
<li><p>Would assume that the EPSG code corresponds to TWD97 as this is Taiwan data and it is also a geographic coordinate system</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>denguesf <span class="ot">&lt;-</span> denguewk <span class="sc">|&gt;</span> <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"最小統計區中心點X"</span>, <span class="st">"最小統計區中心點Y"</span>), <span class="at">crs =</span> <span class="dv">3824</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Checking content after transforming to shapefile</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(denguesf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 25 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 120.1693 ymin: 22.95898 xmax: 120.2361 ymax: 23.01257
Geodetic CRS:  TWD97
      發病日 個案研判日     通報日 性別 年齡層 居住縣市 居住鄉鎮 居住村里
1 2023-07-30 2023/07/31 2023/07/31   女  55-59   台南市   永康區   中興里
2 2023-07-31 2023/08/01 2023/08/01   女  35-39   台南市     東區   崇學里
3 2023-07-31 2023/08/02 2023/08/01   男  50-54   台南市   安平區   平安里
4 2023-08-01 2023/08/03 2023/08/03   男  35-39   台南市   仁德區   成功里
5 2023-08-01 2023/08/02 2023/08/02   女  20-24   台南市     東區   仁和里
6 2023-08-02 2023/08/03 2023/08/03   女  35-39   台南市   永康區   五王里
     最小統計區   一級統計區 二級統計區 感染縣市 感染鄉鎮 感染村里 是否境外移入
1 A6731-0744-00 A6731-58-006   A6731-58   台南市   永康區     None           否
2 A6732-0726-00 A6732-39-009   A6732-39   台南市     東區     None           否
3 A6736-0033-00 A6736-03-004   A6736-03   台南市   安平區     None           否
4 A6727-0158-00 A6727-13-001   A6727-13   台南市   仁德區     None           否
5 A6732-0941-00 A6732-53-007   A6732-53   台南市     東區     None           否
6 A6731-0591-00 A6731-51-002   A6731-51   台南市   永康區     None           否
  感染國家 確定病例數 居住村里代碼 感染村里代碼 血清型 內政部居住縣市代碼
1 中華民國          1  6703100-025         None   None                 67
2 中華民國          1  6703200-004         None   None                 67
3 中華民國          1  6703600-015         None 第一型                 67
4 中華民國          1  6702700-012         None   None                 67
5 中華民國          1  6703200-006         None   None                 67
6 中華民國          1  6703100-001         None   None                 67
  內政部居住鄉鎮代碼 內政部感染縣市代碼 內政部感染鄉鎮代碼 epidemiologyweek
1            6703100                 67            6703100               31
2            6703200                 67            6703200               31
3            6703600                 67            6703600               31
4            6702700                 67            6702700               31
5            6703200                 67            6703200               31
6            6703100                 67            6703100               31
                   geometry
1 POINT (120.2361 23.00695)
2 POINT (120.2231 22.97802)
3 POINT (120.1693 23.00093)
4 POINT (120.2307 22.95898)
5 POINT (120.2347 22.96946)
6 POINT (120.2349 23.01257)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(denguesf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:3824 
  wkt:
GEOGCRS["TWD97",
    DATUM["Taiwan Datum 1997",
        ELLIPSOID["GRS 1980",6378137,298.257222101,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Horizontal component of 3D system."],
        AREA["Taiwan, Republic of China - onshore and offshore - Taiwan Island, Penghu (Pescadores) Islands."],
        BBOX[17.36,114.32,26.96,123.61]],
    ID["EPSG",3824]]</code></pre>
</div>
</div>
</section>
<section id="obtaining-boundary-of-the-study-area" class="level3">
<h3 class="anchored" data-anchor-id="obtaining-boundary-of-the-study-area">3.4.2 Obtaining boundary of the study area</h3>
<ul>
<li>The st_union() function from sf package is used to combine geometries without resolving the boundary</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>Tn_bound <span class="ot">&lt;-</span> Tainan <span class="sc">|&gt;</span> <span class="fu">st_union</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Checking to see if we have obtained the correct study area boundary</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Tn_bound)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="obtaining-dengue-cases-that-are-in-the-study-area" class="level3">
<h3 class="anchored" data-anchor-id="obtaining-dengue-cases-that-are-in-the-study-area">3.4.3 Obtaining dengue cases that are in the study area</h3>
<ul>
<li>The st_intersection() function from sf package is used to find the points that fall into the study area</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>dengue_tn_sf <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(denguesf, Tn_bound)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="deriving-a-dengue-fever-layer-in-spacetime-s3class-of-sfdep" class="level3">
<h3 class="anchored" data-anchor-id="deriving-a-dengue-fever-layer-in-spacetime-s3class-of-sfdep">3.4.4 Deriving a dengue fever layer in spacetime s3class of sfdep</h3>
<ul>
<li><p>mutate() function from the dplyr package is used to change the name of the village name attribute so that it corresponds with the attribute from Tainan sf object. select() from the dplyr package is used to select attributes that are needed and drop those that are not needed.</p></li>
<li><p>There were some missing data from village name attribute from the dengue data. Hence, filter() function from the dplyr package was used to remove those observations with missing data in the village name field. st_drop_geometry() from the sf package is used to drop the geometry field and turn the data into a dataframe.</p></li>
<li><p>left_join() function from the dplyr package was used to join the data and st_drop_geometry() function from sf package was used to drop the geometry field to turn the data into a dataframe.</p></li>
<li><p>is.na() function was used to replace empty data with 0</p></li>
<li><p>Functions from the dplyr package was used to group data by VillCODE and epidemiologyweeks to compute a cases data field showing number of dengue fever cases by village and by epidemiology week. Ungroup() and complete() functions were used to ensure that VILLCODE and epidemiologyweeks that did not have any cases were not dropped and filled with 0 cases.</p></li>
<li><p>filter() function was used to remove week 0s as they are not part of the analysis. as.dataframe() function was used to convert the data in a dataframe.</p></li>
<li><p>spacetime() function from sfdep was used to create a spacetime s3 class object with:</p>
<ol type="1">
<li>A dataframe that has the data field showing number of dengue fever cases by villahe and by epidemiology week.</li>
<li>A sf object that consist of the geospatial information of the boundary each village.</li>
</ol></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dengue_tn_sf <span class="ot">&lt;-</span> dengue_tn_sf <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="st">"VILLNAME"</span> <span class="ot">=</span> 居住村里) <span class="sc">|&gt;</span> <span class="fu">select</span>(VILLNAME, epidemiologyweek, geometry) </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>dengue_prest <span class="ot">&lt;-</span> dengue_tn_sf <span class="sc">|&gt;</span> <span class="fu">filter</span>(VILLNAME <span class="sc">!=</span> <span class="st">"None"</span>) <span class="sc">|&gt;</span> <span class="fu">st_drop_geometry</span>()</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>dengue_prest2 <span class="ot">&lt;-</span> Tainan <span class="sc">|&gt;</span> <span class="fu">left_join</span>(dengue_prest, <span class="at">by =</span> <span class="st">"VILLNAME"</span>) <span class="sc">|&gt;</span> <span class="fu">st_drop_geometry</span>()</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>dengue_prest2[<span class="fu">is.na</span>(dengue_prest2)] <span class="ot">&lt;-</span> <span class="dv">0</span> </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>dengue_prest3 <span class="ot">&lt;-</span> dengue_prest2 <span class="sc">|&gt;</span> </span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(VILLCODE, epidemiologyweek) <span class="sc">|&gt;</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">cases =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">complete</span>(VILLCODE, epidemiologyweek, <span class="at">fill =</span> <span class="fu">list</span>(<span class="at">cases =</span> <span class="dv">0</span>)) </span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>dengue_prest3 <span class="ot">&lt;-</span> dengue_prest3 <span class="sc">|&gt;</span> <span class="fu">filter</span>(epidemiologyweek <span class="sc">!=</span> <span class="dv">0</span>) <span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>()</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>dengue_st <span class="ot">&lt;-</span> <span class="fu">spacetime</span>(<span class="at">.data =</span> dengue_prest3, <span class="at">.geometry =</span> Tainan, <span class="at">.loc_col =</span> <span class="st">"VILLCODE"</span>, <span class="at">.time_col =</span>  <span class="st">"epidemiologyweek"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>is_spacetime() function from sfdep was used to ensure that the spacetime cube was succesfully created.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is_spacetime_cube</span>(dengue_st)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="global-spatial-autocorrelation-analysis" class="level1">
<h1>4 Global Spatial Autocorrelation Analysis</h1>
<section id="deriving-the-spatial-weights" class="level2">
<h2 class="anchored" data-anchor-id="deriving-the-spatial-weights">4.1 Deriving the spatial weights</h2>
<ul>
<li><p>activate() function from the dplyr package is used to activate the geometry context of the spacetime cube</p></li>
<li><p>mutate() function from the dplyrs package is used to create two new attributes nb and wt</p></li>
<li><p>st_contiguity() function from the sfdep package is used to identify neighbours and create a neighbour list for each observation (based on Queen method)</p></li>
<li><p>st_inverse_distance() function from sfdep package is used to derive an inverse distance weights list for each observation</p></li>
<li><p>set_nbs() and set_wts() function is used to activate the data context again and copy over the nb columns to each time-slice.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>dengue_nb <span class="ot">&lt;-</span> dengue_st <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(<span class="st">"geometry"</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">st_contiguity</span>(geometry),</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">wt =</span> <span class="fu">st_inverse_distance</span>(nb, geometry,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">scale =</span> <span class="dv">1</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">alpha =</span> <span class="dv">1</span>),</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_nbs</span>(<span class="st">"nb"</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_wts</span>(<span class="st">"wt"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="computing-global-morans-i" class="level2">
<h2 class="anchored" data-anchor-id="computing-global-morans-i">4.2 Computing Global Moran’s I</h2>
<ul>
<li>global_moran() function from sfdep package is used to compute the Moran’s I value</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>gmoranI <span class="ot">&lt;-</span> <span class="fu">global_moran</span>(dengue_nb<span class="sc">$</span>cases,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                       dengue_nb<span class="sc">$</span>nb,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                       dengue_nb<span class="sc">$</span>wt)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(gmoranI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 2
 $ I: num 0.000623
 $ K: num 20.1</code></pre>
</div>
</div>
<ul>
<li>Global Moran’s I statistic is &gt; 0 which suggest that dengue cases are clustered and dengue cases seems to appear in similar locations.</li>
</ul>
</section>
<section id="performing-global-morans-i-test" class="level2">
<h2 class="anchored" data-anchor-id="performing-global-morans-i-test">4.3 Performing Global Moran’s I test</h2>
<ul>
<li>global_moran_test() function from the sfdep package is used to conduct the Global Moran’s I test</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">global_moran_test</span>(dengue_nb<span class="sc">$</span>cases,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                       dengue_nb<span class="sc">$</span>nb,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                       dengue_nb<span class="sc">$</span>wt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  x  
weights: listw    

Moran I statistic standard deviate = 0.12214, p-value = 0.4514
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
     6.227828e-04     -1.938360e-04      4.470048e-05 </code></pre>
</div>
</div>
<ul>
<li>The p-value from the test is 0.4514 which is &gt; than the alpha value of 0.05, hence, we fail to reject the null hypothesis that the observed spatial distribution of cases of dengue in Tainan is the result of random spatial processes.</li>
</ul>
</section>
<section id="performing-global-morans-i-permutation-test" class="level2">
<h2 class="anchored" data-anchor-id="performing-global-morans-i-permutation-test">4.4 Performing Global Moran’s I permutation test</h2>
<p>The permutation test is conducted when there is doubt that the assumptions of Moran’s I are true (normality and randomization). Monte Carlo simulation is then being employed for the hypothesis testing.</p>
<ul>
<li><p>set.seed() function is used to ensure that computation is reproducible as the test is conducted under Monte Carlo simulation and will vary every time it is being conducted</p></li>
<li><p>global_moran_perm() function from sfdep package is used to perform Monte Carlo simulation</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">global_moran_perm</span>(dengue_nb<span class="sc">$</span>cases,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                       dengue_nb<span class="sc">$</span>nb,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                       dengue_nb<span class="sc">$</span>wt,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">nsim =</span> <span class="dv">99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  x 
weights: listw  
number of simulations + 1: 100 

statistic = 0.00062278, observed rank = 61, p-value = 0.78
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<ul>
<li>Similarly the p-value under Monte Carlo Simulation is 0.78 which is &gt; than the alpha value of 0.05, hence, we do not have sufficient evidence to reject the null hypothesis that the spatial distribution of cases of dengue in the Tainan region resemble random distribution.</li>
</ul>
</section>
</section>
<section id="local-spatial-autocorrelation-analysis" class="level1">
<h1>5 Local Spatial Autocorrelation Analysis</h1>
<section id="computing-local-morans-i" class="level2">
<h2 class="anchored" data-anchor-id="computing-local-morans-i">5.1 Computing Local Moran’s I</h2>
<ul>
<li>local_moran() function from sfdep package is being used to compute local Moran’s I statistic</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>lisa <span class="ot">&lt;-</span> dengue_nb <span class="sc">|&gt;</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">local_moran =</span> <span class="fu">local_moran</span>(</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    cases, nb, wt, <span class="at">nsim =</span> <span class="dv">99</span>),</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(local_moran)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="joining-data" class="level2">
<h2 class="anchored" data-anchor-id="joining-data">5.2 Joining data</h2>
<ul>
<li>left_join() from the dplyr package is being used to join the data to provide geospatial boundary of each village before visualisation</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>tainan_lisa <span class="ot">&lt;-</span> Tainan <span class="sc">|&gt;</span> <span class="fu">left_join</span>(lisa, </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">by =</span> <span class="st">"VILLCODE"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualising-local-morans-i" class="level2">
<h2 class="anchored" data-anchor-id="visualising-local-morans-i">5.3 Visualising Local Moran’s I</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>map1 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(tainan_lisa) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"ii"</span>) <span class="sc">+</span> </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"local Moran's I of Number of Dengue cases"</span>,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>map1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>The local Moran statistic of villages in Tainan mainly ranges from 0 to 20 with a smaller subgroup lying between -20 to 0.</li>
</ul>
</section>
<section id="visualising-p-value-of-local-morans-i-statistic" class="level2">
<h2 class="anchored" data-anchor-id="visualising-p-value-of-local-morans-i-statistic">5.4 Visualising p-value of Local Moran’s I statistic</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>map2 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(tainan_lisa) <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"p_ii_sim"</span>, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"p-value of local Moran's I"</span>,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>map2 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>From the mapping of p-values, we can observed that none of the p-values are statistically significant at an alpha value of 0.05.</li>
</ul>
</section>
<section id="visualising-local-morans-i-and-p-value" class="level2">
<h2 class="anchored" data-anchor-id="visualising-local-morans-i-and-p-value">5.5 Visualising local Moran’s I and p-value</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(map1, map2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="visualising-lisa-map" class="level2">
<h2 class="anchored" data-anchor-id="visualising-lisa-map">5.6 Visualising LISA Map</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>lisa_sig <span class="ot">&lt;-</span> tainan_lisa  <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(p_ii <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>map3 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(tainan_lisa) <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(lisa_sig) <span class="sc">+</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"mean"</span>) <span class="sc">+</span> </span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>   <span class="fu">tm_text</span>(<span class="st">'VILLENG'</span>, <span class="at">size =</span> <span class="fl">0.45</span>, <span class="at">col =</span> <span class="st">"black"</span>) </span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>map3 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p>From the LISA map, we can identify 5 villages which are outliers. They are Xixian Village, Tian Fei Village, Sanhe Village, Zheng Xing Village and Shen Zhou Village. These villages have low amounts of dengue cases but are surrounded by villages with high dengue cases.</p></li>
<li><p>We can also identify 2 clusters which are Ren’ai Village and Liu He village. These village have high dengue cases and are surrounded by villages with high dengue cases as well.</p></li>
<li><p>But, since none of the p-value for the villages are statistically significant we do not have sufficient evidence to conclude that these villages are indeed outliers and clusters.</p></li>
</ul>
</section>
</section>
<section id="emerging-hotspot-analysis" class="level1">
<h1>6 Emerging Hotspot analysis</h1>
<section id="computing-ehsa" class="level2">
<h2 class="anchored" data-anchor-id="computing-ehsa">6.1 Computing EHSA</h2>
<ul>
<li>emerging_hotspot_analysis() function from the sfdep package is used to perform emerging hotspot analysis.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>ehsa <span class="ot">&lt;-</span> <span class="fu">emerging_hotspot_analysis</span>(<span class="at">x =</span> dengue_st, <span class="at">.var =</span> <span class="st">"cases"</span>, <span class="at">k =</span> <span class="dv">1</span>, <span class="at">nsim =</span> <span class="dv">99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualising-the-distribution-of-ehsa-classes" class="level2">
<h2 class="anchored" data-anchor-id="visualising-the-distribution-of-ehsa-classes">6.2 Visualising the distribution of EHSA classes</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ehsa, </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> classification)) <span class="sc">+</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p>From bar-chart, we can identify three emerging hot spot analysis patterns and they are no pattern detected, sporadic cold spot and sporadic hot spot.</p></li>
<li><p>No pattern detected would suggest that the village does not fall into any of the hot or cold spot patterns.</p></li>
<li><p>Sporadic coldspot would suggest that there is a statistically significant cold spot for the final time-step interval with a history of also being an on-again and off-again cold spot. Less than 90 percent of the time-step intervals have been statistically significant cold spots and none of the time-step intervals have been statistically significant hot spots.</p></li>
<li><p>Sporadic hot spot would suggest a statisticallt significant hot spot for the final time-step interval that has a history of also being an on-again and off-again hot spot. Less than 90 percent of the time-step intervals have been statistically significant hot spots and none of the time-step intervals have been significant cold spots.</p></li>
</ul>
</section>
<section id="visualising-ehsa" class="level2">
<h2 class="anchored" data-anchor-id="visualising-ehsa">6.3 Visualising EHSA</h2>
<ul>
<li>joining sf layer with ehsa layer using left_join() from dplyr package to provide Village with geographic context</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>tainan_ehsa <span class="ot">&lt;-</span> Tainan <span class="sc">|&gt;</span> <span class="fu">left_join</span>(ehsa, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"VILLCODE"</span> <span class="ot">=</span> <span class="st">"location"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>ehsa_sig <span class="ot">&lt;-</span> tainan_ehsa <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(p_value <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(tainan_ehsa) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(ehsa_sig) <span class="sc">+</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"classification"</span>) <span class="sc">+</span> </span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_text</span>(<span class="st">'VILLENG'</span>, <span class="at">size =</span> <span class="fl">0.4</span>, <span class="at">col =</span> <span class="st">"white"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="conclusion" class="level1">
<h1>7 Conclusion</h1>
<p>From the Global Spatial Autocorrelation analysis, the Global Moran’s I Statistic was 0.000623 which is bigger than zero and suggest that dengue cases are clustered. But, from the Global Moran’s I test and Global Moran’s Permutation test the P-values were 0.4514 and 0.78 respectively. These P-values are bigger than the alpha values of 0.05, hence I do not have sufficient evidence to reject the null hypothesis that the dengue cases in Tainan are randomly distributed.</p>
<p>From the Local Spatial Autocorrelation Analysis, it was revealed that there were five village outliers (Xixian Village, Tian Fei Village, Sanhe Village, Zheng Xing Village and Shen Zhou Village) with low dengue cases but were surrounded with villages that had high dengue cases. I was also able to find two village clsuters (Ren’ai Village and Liu He village) which had high number of dengue cases and are surrounded by villages with high number of dengue cases as well. But, since none of the P-values for the outlier and cluster villages were bigger than the alpha value of 0.05, I do not have sufficient evidence to conclude that these villages are indeed outliers and clusters.</p>
<p>Lastly, from the emerging hot spot analysis, I was able to identify three emerging hot spot patterns which are no pattern detected, sporadic cold spot and sporadic hot spot. I would suggest for the Taiwanese government to compare the environmental conditions between villages which were identified as sporadic cold spot and sporadic hot spot to find out how they can change the environmental conditions in villages that were identified as hot spots to reduce the number of dengue cases that are emerging from these villages.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>