---
title: "In-class Exercise 05"
---

Loading packages that will be used for the exercise

```{r}
pacman::p_load(sf, sfdep, tmap, tidyverse)
```

Importing data

```{r}
hunan <- st_read(dsn = "data/geospatial", layer = "Hunan")
hunan_2012 <- read.csv("data/aspatial/Hunan_2012.csv")
```

Joining the data

```{r}
hunan_GDPPC <- left_join(hunan, hunan_2012) |> 
  select(1:4, 7, 15)
```

Plotting of choropleth map

```{r}
tmap_mode("plot")
tm_shape(hunan_GDPPC) +
  tm_layout(main.title = "Distribution of GDP per capital by county",
            main.title.position = "center",
            main.title.size = 1.2,
            legend.height = 0.45,
            legend.width = 0.35,
            frame = TRUE) +
  tm_fill('GDPPC',
          style = "quantile",
         palette = "Blues",
         title = "GDPPC") +
  tm_borders(alpha = 0.5) +
  tm_compass(type = "8star", size = 2) +
  tm_scale_bar() +
  tm_grid(alpha = 0.2)
```

Deriving contiguity weights with Queen's method

```{r}
wm_q <- hunan_GDPPC |> 
  mutate(nb = st_contiguity(geometry),
         wt = st_weights(nb, 
                         style = "W"),
         .before = 1)
```

Computing global Moran's I

```{r}
moranI <- global_moran(wm_q$GDPPC,
                       wm_q$nb,
                       wm_q$wt)
glimpse(moranI)
```

Performing Global Moran's I test

```{r}
global_moran_test(wm_q$GDPPC,
                  wm_q$nb,
                  wm_q$wt)
```

Performing Global Moran's I permutation test

```{r}
global_moran_perm(wm_q$GDPPC,
                  wm_q$nb,
                  wm_q$wt,
                  nsim = 99)
```
