<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>IS415-GAA – hands-on_ex01</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Hands on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html" rel="" target="">
 <span class="dropdown-text">Hands on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html" rel="" target="">
 <span class="dropdown-text">Hands on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">In class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex02/In-class_Ex02.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03-NKDE.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex05.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Take-home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html" rel="" target="">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html" rel="" target="">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#loading-packages-that-will-be-used-for-this-exercise" id="toc-loading-packages-that-will-be-used-for-this-exercise" class="nav-link active" data-scroll-target="#loading-packages-that-will-be-used-for-this-exercise">Loading packages that will be used for this exercise</a></li>
  <li><a href="#importing-polygon-feature-data-in-shapefile-format" id="toc-importing-polygon-feature-data-in-shapefile-format" class="nav-link" data-scroll-target="#importing-polygon-feature-data-in-shapefile-format">Importing polygon feature data in shapefile format</a></li>
  <li><a href="#importing-polyline-feature-data-in-shapefile-format" id="toc-importing-polyline-feature-data-in-shapefile-format" class="nav-link" data-scroll-target="#importing-polyline-feature-data-in-shapefile-format">Importing polyline feature data in shapefile format</a></li>
  <li><a href="#importing-other-vector-gis-formats-such-as-in-kml-format" id="toc-importing-other-vector-gis-formats-such-as-in-kml-format" class="nav-link" data-scroll-target="#importing-other-vector-gis-formats-such-as-in-kml-format">Importing other vector GIS formats such as in kml format</a></li>
  <li><a href="#checking-the-content-of-a-simple-feature-dataframe" id="toc-checking-the-content-of-a-simple-feature-dataframe" class="nav-link" data-scroll-target="#checking-the-content-of-a-simple-feature-dataframe">Checking the content of a simple feature dataframe</a></li>
  <li><a href="#learning-more-about-the-associated-attribute-information-in-the-dataframe" id="toc-learning-more-about-the-associated-attribute-information-in-the-dataframe" class="nav-link" data-scroll-target="#learning-more-about-the-associated-attribute-information-in-the-dataframe">Learning more about the associated attribute information in the dataframe</a></li>
  <li><a href="#to-reveal-complete-information-of-a-feature-object-n-number-of-records-to-show" id="toc-to-reveal-complete-information-of-a-feature-object-n-number-of-records-to-show" class="nav-link" data-scroll-target="#to-reveal-complete-information-of-a-feature-object-n-number-of-records-to-show">To reveal complete information of a feature object n = number of records to show</a></li>
  <li><a href="#plotting-of-geospatial-data-plot-function-of-r-graphic-for-visualising-geospatial-feature" id="toc-plotting-of-geospatial-data-plot-function-of-r-graphic-for-visualising-geospatial-feature" class="nav-link" data-scroll-target="#plotting-of-geospatial-data-plot-function-of-r-graphic-for-visualising-geospatial-feature">Plotting of Geospatial data plot(): function of R Graphic for visualising geospatial feature</a></li>
  <li><a href="#plotting-of-only-the-geometry-field" id="toc-plotting-of-only-the-geometry-field" class="nav-link" data-scroll-target="#plotting-of-only-the-geometry-field">Plotting of only the geometry field</a></li>
  <li><a href="#plotting-of-specific-attribute-of-an-sf-object" id="toc-plotting-of-specific-attribute-of-an-sf-object" class="nav-link" data-scroll-target="#plotting-of-specific-attribute-of-an-sf-object">Plotting of specific attribute of an sf object</a></li>
  <li><a href="#obtaining-coordinate-system-of-a-simple-feature-dataframe" id="toc-obtaining-coordinate-system-of-a-simple-feature-dataframe" class="nav-link" data-scroll-target="#obtaining-coordinate-system-of-a-simple-feature-dataframe">Obtaining coordinate system of a simple feature dataframe</a></li>
  <li><a href="#assigning-epsg-code-to-a-simple-feature-dataframe" id="toc-assigning-epsg-code-to-a-simple-feature-dataframe" class="nav-link" data-scroll-target="#assigning-epsg-code-to-a-simple-feature-dataframe">Assigning EPSG code to a simple feature dataframe</a></li>
  <li><a href="#transforming-projection" id="toc-transforming-projection" class="nav-link" data-scroll-target="#transforming-projection">Transforming projection</a></li>
  <li><a href="#importing-aspatial-data" id="toc-importing-aspatial-data" class="nav-link" data-scroll-target="#importing-aspatial-data">Importing aspatial data</a></li>
  <li><a href="#examining-the-datafile" id="toc-examining-the-datafile" class="nav-link" data-scroll-target="#examining-the-datafile">Examining the datafile</a></li>
  <li><a href="#creating-a-simple-feature-dataframe-from-an-aspatial-dataframe-and-transformation-of-coordinate-system" id="toc-creating-a-simple-feature-dataframe-from-an-aspatial-dataframe-and-transformation-of-coordinate-system" class="nav-link" data-scroll-target="#creating-a-simple-feature-dataframe-from-an-aspatial-dataframe-and-transformation-of-coordinate-system">Creating a simple feature dataframe from an aspatial dataframe and transformation of coordinate system</a></li>
  <li><a href="#performing-buffering" id="toc-performing-buffering" class="nav-link" data-scroll-target="#performing-buffering">Performing buffering</a></li>
  <li><a href="#plotting-histogram-to-reveal-distributnio-of-presch-density" id="toc-plotting-histogram-to-reveal-distributnio-of-presch-density" class="nav-link" data-scroll-target="#plotting-histogram-to-reveal-distributnio-of-presch-density">Plotting histogram to reveal distributnio of PreSch Density</a></li>
  <li><a href="#plotting-of-scatterplot-showing-relationship-between-pre-school-density-and-pre-school-count" id="toc-plotting-of-scatterplot-showing-relationship-between-pre-school-density-and-pre-school-count" class="nav-link" data-scroll-target="#plotting-of-scatterplot-showing-relationship-between-pre-school-density-and-pre-school-count">Plotting of scatterplot showing relationship between Pre-school Density and Pre-school count</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">



<hr>
<p>title: “Hands-on Exercise 01: Geospatial Data Science with R”</p>
<hr>
<section id="loading-packages-that-will-be-used-for-this-exercise" class="level2">
<h2 class="anchored" data-anchor-id="loading-packages-that-will-be-used-for-this-exercise">Loading packages that will be used for this exercise</h2>
<ol type="1">
<li>sf: It is for importing, managing, and processing geospatial data</li>
<li>Tidyverse: It is for performing data science tasks such as importing, wrangling and visualising data Tidyverse consist of a family of R packages that includes:</li>
</ol>
<ul>
<li>readr: for importing csv data</li>
<li>readxl: for importing excel worksheets</li>
<li>tidyr: for manipulating data</li>
<li>dplyr: for data wrangling</li>
<li>ggplot2: for visualising data</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>alternatively, library() can be used to load a single package.</p>
</section>
<section id="importing-polygon-feature-data-in-shapefile-format" class="level2">
<h2 class="anchored" data-anchor-id="importing-polygon-feature-data-in-shapefile-format">Importing polygon feature data in shapefile format</h2>
<p>MP14_SUBZONE_WEB_PL is a shapefile and st_read() function of the sf package can be used to import it as a polygon feature dataframe</p>
<p>There are two arguments that are needed for shapefile format:</p>
<ol type="1">
<li><p>dsn = define the file directory of the data path</p></li>
<li><p>layer = provide the name of the shapefile. Do not need to include the extension.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mpsz <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>, <span class="at">layer =</span> <span class="st">"MP14_SUBZONE_WEB_PL"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `MP14_SUBZONE_WEB_PL' from data source 
  `/Users/chuangjinlei/Desktop/JinLei13/IS415-GAA/Hands-on_Ex/Hands-on_Ex01/data/geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 323 features and 15 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33
Projected CRS: SVY21</code></pre>
</div>
</div>
<ul>
<li>Reveals that the geospatial objects are multipolygon features</li>
<li>There are a total of 323 multipolygon features and 15 fields in mpsz</li>
<li>It is in svy21 projected coordinate system</li>
</ul>
</section>
<section id="importing-polyline-feature-data-in-shapefile-format" class="level2">
<h2 class="anchored" data-anchor-id="importing-polyline-feature-data-in-shapefile-format">Importing polyline feature data in shapefile format</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>cyclingpath <span class="ot">=</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>, </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">layer =</span> <span class="st">"CyclingPathGazette"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `CyclingPathGazette' from data source 
  `/Users/chuangjinlei/Desktop/JinLei13/IS415-GAA/Hands-on_Ex/Hands-on_Ex01/data/geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 2558 features and 2 fields
Geometry type: MULTILINESTRING
Dimension:     XY
Bounding box:  xmin: 11854.32 ymin: 28347.98 xmax: 42626.09 ymax: 48948.15
Projected CRS: SVY21</code></pre>
</div>
</div>
<ul>
<li>Reveals that the geospatial objects are in Multilinestring features</li>
<li>There are a total of 2558 multilinestring features with 2 fields</li>
<li>It is in svy21 projected coordinate system</li>
</ul>
</section>
<section id="importing-other-vector-gis-formats-such-as-in-kml-format" class="level2">
<h2 class="anchored" data-anchor-id="importing-other-vector-gis-formats-such-as-in-kml-format">Importing other vector GIS formats such as in kml format</h2>
<p>Using the same st_read function from sf package but the complete path and kml file extension needs to be provided</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>preschool <span class="ot">=</span> <span class="fu">st_read</span>(<span class="st">"data/geospatial/PreSchoolsLocation.kml"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `PRESCHOOLS_LOCATION' from data source 
  `/Users/chuangjinlei/Desktop/JinLei13/IS415-GAA/Hands-on_Ex/Hands-on_Ex01/data/geospatial/PreSchoolsLocation.kml' 
  using driver `KML'
Simple feature collection with 2290 features and 2 fields
Geometry type: POINT
Dimension:     XYZ
Bounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134
z_range:       zmin: 0 zmax: 0
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<ul>
<li>Reveals that preschool is a point feature dataframe</li>
<li>There are a total of 2290 point features with 2 fields</li>
<li>The coordinate system for preschool is in wgs84</li>
</ul>
</section>
<section id="checking-the-content-of-a-simple-feature-dataframe" class="level2">
<h2 class="anchored" data-anchor-id="checking-the-content-of-a-simple-feature-dataframe">Checking the content of a simple feature dataframe</h2>
<p>We can retrieve the geometry list-column using</p>
<ol type="1">
<li><p>mpsz$geometry: retrieved using the name of the field/variable</p></li>
<li><p>mpsz[[16]]: retrieved using the index number of the field</p></li>
<li><p>st_geometry(mpsz): st_geometry() function directly pulls out the information from the simple feature dataframe</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mpsz<span class="sc">$</span>geometry</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 323 features 
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33
Projected CRS: SVY21
First 5 geometries:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((31495.56 30140.01, 31980.96 296...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((29092.28 30021.89, 29119.64 300...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((29932.33 29879.12, 29947.32 298...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((27131.28 30059.73, 27088.33 297...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((26451.03 30396.46, 26440.47 303...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mpsz[[<span class="dv">16</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 323 features 
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33
Projected CRS: SVY21
First 5 geometries:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((31495.56 30140.01, 31980.96 296...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((29092.28 30021.89, 29119.64 300...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((29932.33 29879.12, 29947.32 298...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((27131.28 30059.73, 27088.33 297...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((26451.03 30396.46, 26440.47 303...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 323 features 
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33
Projected CRS: SVY21
First 5 geometries:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((31495.56 30140.01, 31980.96 296...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((29092.28 30021.89, 29119.64 300...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((29932.33 29879.12, 29947.32 298...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((27131.28 30059.73, 27088.33 297...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((26451.03 30396.46, 26440.47 303...</code></pre>
</div>
</div>
<ul>
<li>Provides basic information of the feature class such as geometry, the geographic extent of the features and the coordinate system of the data</li>
</ul>
</section>
<section id="learning-more-about-the-associated-attribute-information-in-the-dataframe" class="level2">
<h2 class="anchored" data-anchor-id="learning-more-about-the-associated-attribute-information-in-the-dataframe">Learning more about the associated attribute information in the dataframe</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 323
Columns: 16
$ OBJECTID   &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, …
$ SUBZONE_NO &lt;int&gt; 1, 1, 3, 8, 3, 7, 9, 2, 13, 7, 12, 6, 1, 5, 1, 1, 3, 2, 2, …
$ SUBZONE_N  &lt;chr&gt; "MARINA SOUTH", "PEARL'S HILL", "BOAT QUAY", "HENDERSON HIL…
$ SUBZONE_C  &lt;chr&gt; "MSSZ01", "OTSZ01", "SRSZ03", "BMSZ08", "BMSZ03", "BMSZ07",…
$ CA_IND     &lt;chr&gt; "Y", "Y", "Y", "N", "N", "N", "N", "Y", "N", "N", "N", "N",…
$ PLN_AREA_N &lt;chr&gt; "MARINA SOUTH", "OUTRAM", "SINGAPORE RIVER", "BUKIT MERAH",…
$ PLN_AREA_C &lt;chr&gt; "MS", "OT", "SR", "BM", "BM", "BM", "BM", "SR", "QT", "QT",…
$ REGION_N   &lt;chr&gt; "CENTRAL REGION", "CENTRAL REGION", "CENTRAL REGION", "CENT…
$ REGION_C   &lt;chr&gt; "CR", "CR", "CR", "CR", "CR", "CR", "CR", "CR", "CR", "CR",…
$ INC_CRC    &lt;chr&gt; "5ED7EB253F99252E", "8C7149B9EB32EEFC", "C35FEFF02B13E0E5",…
$ FMEL_UPD_D &lt;date&gt; 2014-12-05, 2014-12-05, 2014-12-05, 2014-12-05, 2014-12-05…
$ X_ADDR     &lt;dbl&gt; 31595.84, 28679.06, 29654.96, 26782.83, 26201.96, 25358.82,…
$ Y_ADDR     &lt;dbl&gt; 29220.19, 29782.05, 29974.66, 29933.77, 30005.70, 29991.38,…
$ SHAPE_Leng &lt;dbl&gt; 5267.381, 3506.107, 1740.926, 3313.625, 2825.594, 4428.913,…
$ SHAPE_Area &lt;dbl&gt; 1630379.27, 559816.25, 160807.50, 595428.89, 387429.44, 103…
$ geometry   &lt;MULTIPOLYGON [m]&gt; MULTIPOLYGON (((31495.56 30..., MULTIPOLYGON (…</code></pre>
</div>
</div>
<ul>
<li>glimpse() function in dplyr reveals the data type of each field.</li>
</ul>
</section>
<section id="to-reveal-complete-information-of-a-feature-object-n-number-of-records-to-show" class="level2">
<h2 class="anchored" data-anchor-id="to-reveal-complete-information-of-a-feature-object-n-number-of-records-to-show">To reveal complete information of a feature object n = number of records to show</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mpsz, <span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 5 features and 15 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 25867.68 ymin: 28369.47 xmax: 32362.39 ymax: 30435.54
Projected CRS: SVY21
  OBJECTID SUBZONE_NO      SUBZONE_N SUBZONE_C CA_IND      PLN_AREA_N
1        1          1   MARINA SOUTH    MSSZ01      Y    MARINA SOUTH
2        2          1   PEARL'S HILL    OTSZ01      Y          OUTRAM
3        3          3      BOAT QUAY    SRSZ03      Y SINGAPORE RIVER
4        4          8 HENDERSON HILL    BMSZ08      N     BUKIT MERAH
5        5          3        REDHILL    BMSZ03      N     BUKIT MERAH
  PLN_AREA_C       REGION_N REGION_C          INC_CRC FMEL_UPD_D   X_ADDR
1         MS CENTRAL REGION       CR 5ED7EB253F99252E 2014-12-05 31595.84
2         OT CENTRAL REGION       CR 8C7149B9EB32EEFC 2014-12-05 28679.06
3         SR CENTRAL REGION       CR C35FEFF02B13E0E5 2014-12-05 29654.96
4         BM CENTRAL REGION       CR 3775D82C5DDBEFBD 2014-12-05 26782.83
5         BM CENTRAL REGION       CR 85D9ABEF0A40678F 2014-12-05 26201.96
    Y_ADDR SHAPE_Leng SHAPE_Area                       geometry
1 29220.19   5267.381  1630379.3 MULTIPOLYGON (((31495.56 30...
2 29782.05   3506.107   559816.2 MULTIPOLYGON (((29092.28 30...
3 29974.66   1740.926   160807.5 MULTIPOLYGON (((29932.33 29...
4 29933.77   3313.625   595428.9 MULTIPOLYGON (((27131.28 30...
5 30005.70   2825.594   387429.4 MULTIPOLYGON (((26451.03 30...</code></pre>
</div>
</div>
</section>
<section id="plotting-of-geospatial-data-plot-function-of-r-graphic-for-visualising-geospatial-feature" class="level2">
<h2 class="anchored" data-anchor-id="plotting-of-geospatial-data-plot-function-of-r-graphic-for-visualising-geospatial-feature">Plotting of Geospatial data plot(): function of R Graphic for visualising geospatial feature</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: plotting the first 9 out of 15 attributes; use max.plot = 15 to plot
all</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex01_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>The default plot of an sf object is a multi-plot of all attributes up to a reasonable maximum.</li>
</ul>
</section>
<section id="plotting-of-only-the-geometry-field" class="level2">
<h2 class="anchored" data-anchor-id="plotting-of-only-the-geometry-field">Plotting of only the geometry field</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(mpsz))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpsz<span class="sc">$</span>geometry)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex01_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpsz[[<span class="dv">16</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plotting-of-specific-attribute-of-an-sf-object" class="level2">
<h2 class="anchored" data-anchor-id="plotting-of-specific-attribute-of-an-sf-object">Plotting of specific attribute of an sf object</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpsz[<span class="st">"PLN_AREA_N"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex01_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="obtaining-coordinate-system-of-a-simple-feature-dataframe" class="level2">
<h2 class="anchored" data-anchor-id="obtaining-coordinate-system-of-a-simple-feature-dataframe">Obtaining coordinate system of a simple feature dataframe</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: SVY21 
  wkt:
PROJCRS["SVY21",
    BASEGEOGCRS["SVY21[WGS84]",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6326]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CONVERSION["unnamed",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",1.36666666666667,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",103.833333333333,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",28001.642,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",38744.572,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]</code></pre>
</div>
</div>
<ul>
<li>mpsz is projected in svy21</li>
<li>EPSG is 9001</li>
<li>EPSG code for svy21 should be 3414</li>
</ul>
</section>
<section id="assigning-epsg-code-to-a-simple-feature-dataframe" class="level2">
<h2 class="anchored" data-anchor-id="assigning-epsg-code-to-a-simple-feature-dataframe">Assigning EPSG code to a simple feature dataframe</h2>
<ol type="1">
<li><p>used when projected system and EPSG code does not match</p></li>
<li><p>This does not re-project the data</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>mpsz3414 <span class="ot">&lt;-</span> <span class="fu">st_set_crs</span>(mpsz, <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: st_crs&lt;- : replacing crs does not reproject data; use st_transform for
that</code></pre>
</div>
</div>
<p>Checking EPSG code again</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(mpsz3414)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:3414 
  wkt:
PROJCRS["SVY21 / Singapore TM",
    BASEGEOGCRS["SVY21",
        DATUM["SVY21",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4757]],
    CONVERSION["Singapore Transverse Mercator",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",1.36666666666667,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",103.833333333333,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",28001.642,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",38744.572,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["northing (N)",north,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (E)",east,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Cadastre, engineering survey, topographic mapping."],
        AREA["Singapore - onshore and offshore."],
        BBOX[1.13,103.59,1.47,104.07]],
    ID["EPSG",3414]]</code></pre>
</div>
</div>
</section>
<section id="transforming-projection" class="level2">
<h2 class="anchored" data-anchor-id="transforming-projection">Transforming projection</h2>
<ul>
<li><p>st_transform(): This is used to re-project a feature object from one coordinate system to another mathematically</p></li>
<li><p>This is done to ensure that both geospatial data are projected using similar coordinate system</p></li>
<li><p>Also used to transform original data from geographic coordinate system to projected coordinate system as GCS is not appropriate for distance and area analysis</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>preschool3414 <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(preschool, <span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>In practice, we need to find out the appropriate project coordinate system to use for the analysis before performing the projection transformation</li>
</ul>
<p>Checking the coordinate system of preschool after transformation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(preschool3414)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 2290 features 
Geometry type: POINT
Dimension:     XYZ
Bounding box:  xmin: 11810.03 ymin: 25596.33 xmax: 45404.24 ymax: 49300.88
z_range:       zmin: 0 zmax: 0
Projected CRS: SVY21 / Singapore TM
First 5 geometries:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (25089.46 31299.16 0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (27189.07 32792.54 0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (28844.56 36773.76 0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (24821.92 46303.16 0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (28637.82 35038.49 0)</code></pre>
</div>
</div>
</section>
<section id="importing-aspatial-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-aspatial-data">Importing aspatial data</h2>
<p>Aspatial data: geospatial data is not among the fields.</p>
<ul>
<li><p>Instead, there are two fields that capture the x and y coordinates for the data points. Such as csv format</p></li>
<li><p>We can use read_csv from the readr package The complete file directory and extension must be included</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>listings <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/listings.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 3457 Columns: 75
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (25): listing_url, source, name, neighborhood_overview, picture_url, ho...
dbl  (36): id, scrape_id, host_id, host_listings_count, host_total_listings_...
lgl   (9): description, host_is_superhost, host_has_profile_pic, host_identi...
date  (5): last_scraped, host_since, calendar_last_scraped, first_review, la...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="examining-the-datafile" class="level2">
<h2 class="anchored" data-anchor-id="examining-the-datafile">Examining the datafile</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(listings)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
# A tibble: 3,457 × 75
       id listing_url    scrap…¹ last_scr…² source name  descr…³ neigh…⁴ pictu…⁵
    &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt; &lt;date&gt;     &lt;chr&gt;  &lt;chr&gt; &lt;lgl&gt;   &lt;chr&gt;   &lt;chr&gt;  
 1  71609 https://www.a… 2.02e13 2023-12-27 previ… Vill… NA      &lt;NA&gt;    https:…
 2  71896 https://www.a… 2.02e13 2023-12-26 city … Home… NA      &lt;NA&gt;    https:…
 3  71903 https://www.a… 2.02e13 2023-12-26 city … Home… NA      Quiet … https:…
 4 275343 https://www.a… 2.02e13 2023-12-26 city … Rent… NA      &lt;NA&gt;    https:…
 5 275344 https://www.a… 2.02e13 2023-12-26 city … Rent… NA      Bus st… https:…
 6 289234 https://www.a… 2.02e13 2023-12-27 previ… Home… NA      A quie… https:…
 7 294281 https://www.a… 2.02e13 2023-12-27 city … Rent… NA      &lt;NA&gt;    https:…
 8 324945 https://www.a… 2.02e13 2023-12-26 city … Rent… NA      &lt;NA&gt;    https:…
 9 330095 https://www.a… 2.02e13 2023-12-26 city … Rent… NA      Near I… https:…
10 369141 https://www.a… 2.02e13 2023-12-27 city … Plac… NA      DO YOU… https:…
# … with 3,447 more rows, 66 more variables: host_id &lt;dbl&gt;, host_url &lt;chr&gt;,
#   host_name &lt;chr&gt;, host_since &lt;date&gt;, host_location &lt;chr&gt;, host_about &lt;chr&gt;,
#   host_response_time &lt;chr&gt;, host_response_rate &lt;chr&gt;,
#   host_acceptance_rate &lt;chr&gt;, host_is_superhost &lt;lgl&gt;,
#   host_thumbnail_url &lt;chr&gt;, host_picture_url &lt;chr&gt;, host_neighbourhood &lt;chr&gt;,
#   host_listings_count &lt;dbl&gt;, host_total_listings_count &lt;dbl&gt;,
#   host_verifications &lt;chr&gt;, host_has_profile_pic &lt;lgl&gt;, …</code></pre>
</div>
</div>
</section>
<section id="creating-a-simple-feature-dataframe-from-an-aspatial-dataframe-and-transformation-of-coordinate-system" class="level2">
<h2 class="anchored" data-anchor-id="creating-a-simple-feature-dataframe-from-an-aspatial-dataframe-and-transformation-of-coordinate-system">Creating a simple feature dataframe from an aspatial dataframe and transformation of coordinate system</h2>
<ol type="1">
<li><p>coords argument: requires you to provide the column and of the x-coordinates and then the column name of the y-coordinates</p></li>
<li><p>crs argument: requires you to provide the coordinate system in EPSG code format. (EPSG 4326 is wgs84 Geogpraphic Coordinate System)</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>listings_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(listings, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs=</span><span class="dv">4326</span>) <span class="sc">|&gt;</span> <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Examining the content of the newly created simple feature data frame</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(listings_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,457
Columns: 74
$ id                                           &lt;dbl&gt; 71609, 71896, 71903, 2753…
$ listing_url                                  &lt;chr&gt; "https://www.airbnb.com/r…
$ scrape_id                                    &lt;dbl&gt; 2.023123e+13, 2.023123e+1…
$ last_scraped                                 &lt;date&gt; 2023-12-27, 2023-12-26, …
$ source                                       &lt;chr&gt; "previous scrape", "city …
$ name                                         &lt;chr&gt; "Villa in Singapore · ★4.…
$ description                                  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, N…
$ neighborhood_overview                        &lt;chr&gt; NA, NA, "Quiet and view o…
$ picture_url                                  &lt;chr&gt; "https://a0.muscache.com/…
$ host_id                                      &lt;dbl&gt; 367042, 367042, 367042, 1…
$ host_url                                     &lt;chr&gt; "https://www.airbnb.com/u…
$ host_name                                    &lt;chr&gt; "Belinda", "Belinda", "Be…
$ host_since                                   &lt;date&gt; 2011-01-29, 2011-01-29, …
$ host_location                                &lt;chr&gt; "Singapore", "Singapore",…
$ host_about                                   &lt;chr&gt; "Hi My name is Belinda -H…
$ host_response_time                           &lt;chr&gt; "N/A", "N/A", "N/A", "wit…
$ host_response_rate                           &lt;chr&gt; "N/A", "N/A", "N/A", "100…
$ host_acceptance_rate                         &lt;chr&gt; "100%", "100%", "100%", "…
$ host_is_superhost                            &lt;lgl&gt; FALSE, FALSE, FALSE, FALS…
$ host_thumbnail_url                           &lt;chr&gt; "https://a0.muscache.com/…
$ host_picture_url                             &lt;chr&gt; "https://a0.muscache.com/…
$ host_neighbourhood                           &lt;chr&gt; "Tampines", "Tampines", "…
$ host_listings_count                          &lt;dbl&gt; 5, 5, 5, 51, 51, 5, 7, 51…
$ host_total_listings_count                    &lt;dbl&gt; 15, 15, 15, 68, 68, 15, 8…
$ host_verifications                           &lt;chr&gt; "['email', 'phone']", "['…
$ host_has_profile_pic                         &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, T…
$ host_identity_verified                       &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, T…
$ neighbourhood                                &lt;chr&gt; NA, NA, "Singapore, Singa…
$ neighbourhood_cleansed                       &lt;chr&gt; "Tampines", "Tampines", "…
$ neighbourhood_group_cleansed                 &lt;chr&gt; "East Region", "East Regi…
$ property_type                                &lt;chr&gt; "Private room in villa", …
$ room_type                                    &lt;chr&gt; "Private room", "Private …
$ accommodates                                 &lt;dbl&gt; 3, 1, 2, 1, 1, 4, 2, 1, 1…
$ bathrooms                                    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, N…
$ bathrooms_text                               &lt;chr&gt; "1 private bath", "Shared…
$ bedrooms                                     &lt;lgl&gt; NA, NA, NA, NA, NA, NA, N…
$ beds                                         &lt;dbl&gt; 3, 1, 2, 1, 1, 5, 1, 1, 1…
$ amenities                                    &lt;chr&gt; "[]", "[]", "[]", "[]", "…
$ price                                        &lt;chr&gt; "$150.00", "$80.00", "$80…
$ minimum_nights                               &lt;dbl&gt; 92, 92, 92, 60, 60, 92, 9…
$ maximum_nights                               &lt;dbl&gt; 365, 365, 365, 999, 999, …
$ minimum_minimum_nights                       &lt;dbl&gt; 92, 92, 92, 60, 60, 92, 9…
$ maximum_minimum_nights                       &lt;dbl&gt; 92, 92, 92, 60, 60, 92, 9…
$ minimum_maximum_nights                       &lt;dbl&gt; 1125, 1125, 1125, 1125, 1…
$ maximum_maximum_nights                       &lt;dbl&gt; 1125, 1125, 1125, 1125, 1…
$ minimum_nights_avg_ntm                       &lt;dbl&gt; 92, 92, 92, 60, 60, 92, 9…
$ maximum_nights_avg_ntm                       &lt;dbl&gt; 1125, 1125, 1125, 1125, 1…
$ calendar_updated                             &lt;lgl&gt; NA, NA, NA, NA, NA, NA, N…
$ has_availability                             &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, T…
$ availability_30                              &lt;dbl&gt; 30, 30, 30, 6, 6, 29, 30,…
$ availability_60                              &lt;dbl&gt; 34, 60, 60, 6, 6, 33, 60,…
$ availability_90                              &lt;dbl&gt; 55, 90, 90, 6, 6, 54, 90,…
$ availability_365                             &lt;dbl&gt; 55, 91, 91, 183, 183, 54,…
$ calendar_last_scraped                        &lt;date&gt; 2023-12-27, 2023-12-26, …
$ number_of_reviews                            &lt;dbl&gt; 19, 24, 46, 20, 16, 12, 1…
$ number_of_reviews_ltm                        &lt;dbl&gt; 0, 0, 0, 0, 3, 0, 0, 1, 2…
$ number_of_reviews_l30d                       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ first_review                                 &lt;date&gt; 2011-12-19, 2011-07-30, …
$ last_review                                  &lt;date&gt; 2020-01-17, 2019-10-13, …
$ review_scores_rating                         &lt;dbl&gt; 4.44, 4.16, 4.41, 4.40, 4…
$ review_scores_accuracy                       &lt;dbl&gt; 4.37, 4.22, 4.39, 4.16, 4…
$ review_scores_cleanliness                    &lt;dbl&gt; 4.00, 4.09, 4.52, 4.26, 4…
$ review_scores_checkin                        &lt;dbl&gt; 4.63, 4.43, 4.63, 4.47, 4…
$ review_scores_communication                  &lt;dbl&gt; 4.78, 4.43, 4.64, 4.42, 4…
$ review_scores_location                       &lt;dbl&gt; 4.26, 4.17, 4.50, 4.53, 4…
$ review_scores_value                          &lt;dbl&gt; 4.32, 4.04, 4.36, 4.63, 4…
$ license                                      &lt;chr&gt; NA, NA, NA, "S0399", "S03…
$ instant_bookable                             &lt;lgl&gt; FALSE, FALSE, FALSE, TRUE…
$ calculated_host_listings_count               &lt;dbl&gt; 5, 5, 5, 51, 51, 5, 7, 51…
$ calculated_host_listings_count_entire_homes  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 1, 0, 0…
$ calculated_host_listings_count_private_rooms &lt;dbl&gt; 5, 5, 5, 51, 51, 5, 6, 51…
$ calculated_host_listings_count_shared_rooms  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ reviews_per_month                            &lt;dbl&gt; 0.13, 0.16, 0.30, 0.15, 0…
$ geometry                                     &lt;POINT [m]&gt; POINT (41972.5 3639…</code></pre>
</div>
</div>
<ul>
<li>A new column called geometry has been added into the dataframe</li>
<li>Longitude and latitude column has been removed as well</li>
</ul>
</section>
<section id="performing-buffering" class="level2">
<h2 class="anchored" data-anchor-id="performing-buffering">Performing buffering</h2>
<ul>
<li><p>st_buffer(): used to compute the 5-meter buffers around cycling paths</p></li>
<li><p>st_area(): used to calculate the area of the buffers</p></li>
<li><p>sum(): used to derive the total land involve in the buffer</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>buffer_cycling <span class="ot">&lt;-</span> <span class="fu">st_buffer</span>(cyclingpath, <span class="at">dist=</span><span class="dv">5</span>, <span class="at">nQuadSegs =</span> <span class="dv">30</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>buffer_cycling<span class="sc">$</span>AREA <span class="ot">&lt;-</span> <span class="fu">st_area</span>(buffer_cycling) <span class="co">#New attribute of area is added</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(buffer_cycling<span class="sc">$</span>AREA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1774367 [m^2]</code></pre>
</div>
</div>
<p>Performing Point-in-polygon count</p>
<ul>
<li><p>st_intersects(): compares two sf data objects where they touch or overlap</p></li>
<li><p>lengths(): calculate numbers of pre-schools that fall inside each planning subzone</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span><span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(mpsz3414, preschool3414)) <span class="co">#Adds a new attribute PreSch Count </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Check the summary statistic of the newly derived PreSch Count field</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    0.00    4.00    7.09   10.00   72.00 </code></pre>
</div>
</div>
<p>Obtaining the planning subzone with the most number of pre-schools</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">top_n</span>(mpsz3414, <span class="dv">1</span>, <span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1 feature and 16 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 39655.33 ymin: 35966 xmax: 42940.57 ymax: 38622.37
Projected CRS: SVY21 / Singapore TM
  OBJECTID SUBZONE_NO     SUBZONE_N SUBZONE_C CA_IND PLN_AREA_N PLN_AREA_C
1      189          2 TAMPINES EAST    TMSZ02      N   TAMPINES         TM
     REGION_N REGION_C          INC_CRC FMEL_UPD_D   X_ADDR   Y_ADDR SHAPE_Leng
1 EAST REGION       ER 21658EAAF84F4D8D 2014-12-05 41122.55 37392.39   10180.62
  SHAPE_Area                       geometry PreSch Count
1    4339824 MULTIPOLYGON (((42196.76 38...           72</code></pre>
</div>
</div>
<p>Can control number of top results to show in the second argument</p>
<p>Calculating density of pre-school by planning subzone</p>
<ol type="1">
<li><p>st_area(): calculates area of each planning subzone</p></li>
<li><p>mutate(): used to compute the density of pre-school</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>mpsz3414<span class="sc">$</span>Area <span class="ot">&lt;-</span> mpsz3414 <span class="sc">|&gt;</span> <span class="fu">st_area</span>()</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>mpsz3414 <span class="ot">&lt;-</span> mpsz3414 <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span><span class="sc">/</span>Area <span class="sc">*</span> <span class="dv">1000000</span>)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Units: [1/m^2]
  [1]  0.00000000 10.71780258  0.00000000  8.39730842  7.74334547 12.61671938
  [7]  9.06237005  3.44608163 10.14018978  1.58316954  2.18956299  6.80952137
 [13]  0.00000000  2.54735962 11.84392175  0.00000000  0.00000000  0.00000000
 [19]  0.00000000  0.81315153  0.00000000  9.68631056  0.00000000  1.85073158
 [25] 14.44946739 15.70722567 35.60169297  5.47445116  8.24839976  8.20434375
 [31]  0.00000000  0.00000000  9.03949026  0.00000000  9.71527392 17.02931505
 [37] 25.35629701 15.89256712  0.00000000 13.38904412  0.00000000  8.55218466
 [43]  3.81906935  0.00000000  3.38235947  0.00000000 19.99473290  1.40732345
 [49] 12.02109308  0.00000000  0.56949216 11.73904083  3.03547315 11.71891220
 [55] 10.85531796  0.00000000  9.01009096  3.56920079  9.33487616  0.00000000
 [61]  5.62143826  0.00000000  3.14611804 11.92319670 17.95935646  0.00000000
 [67]  6.33635532  1.23223830  8.16982496  3.22047037  2.88466396  4.61097285
 [73]  2.21008233  7.16844116  0.00000000  0.00000000  2.73265431 10.44144783
 [79]  0.00000000  0.00000000  2.97422984  0.00000000  6.51394463  1.83998165
 [85]  7.18639790  0.00000000  0.00000000  8.94837720  0.00000000  3.33955886
 [91]  4.15173953  1.56834350  0.00000000  0.00000000  5.20000413  0.00000000
 [97]  0.00000000 10.30968514  0.00000000  4.70115955  9.74215067  0.00000000
[103] 12.06878367  0.00000000  4.07884557  2.10935105  1.51390154  9.67535043
[109] 13.07350901 10.89990666  0.00000000  0.00000000  5.19103594 10.30880422
[115]  0.00000000  7.01713427  9.63440559 20.38940000 15.23241557  8.06817176
[121]  4.68205034  0.00000000  0.00000000  0.00000000 12.36993726  7.91653219
[127]  8.54111363  0.00000000  0.00000000 10.69456841  4.89096905 12.16561160
[133]  9.52960696  4.88405365  9.01512182  1.47366674  5.85700658 10.37164559
[139] 12.51674977  0.00000000  7.29210328 19.10870511  0.47660433  0.00000000
[145]  3.68829945 16.16927644  0.00000000  6.74841182  6.38259016 11.89494629
[151]  5.53540338 19.93540015  5.46371947  1.92511630  0.00000000  2.27575881
[157]  5.67555548  0.00000000  4.54910663 10.71119235 13.44562546  0.00000000
[163] 13.51640116  1.85331931 15.58492435  0.00000000  8.37766375 14.12657723
[169]  1.95164673  6.20374534  3.45088937 14.34376095 13.15091082 13.29829289
[175] 11.24580300 13.35468154 16.72740917  0.00000000  0.00000000 10.35889471
[181]  7.24451415 10.93459135  8.97465652  0.00000000  7.37272771  9.67347180
[187]  2.53171832  1.20734381 16.59053403  5.01097143  0.00000000  5.15369283
[193] 14.50388766  5.93156946  2.43923377  3.10983090  7.12358161  8.11313906
[199] 11.86142055 16.25624119  0.00000000 17.80061264  0.00000000 11.91173402
[205]  4.47169158 12.07188321 20.10817016 12.04024877  0.00000000  9.17210690
[211]  7.58573627  5.48018382  1.02119062  7.19777707 17.38652500 16.41994474
[217]  7.09104861 13.18514448 12.97933967  5.46797281  0.00000000 19.44784751
[223]  8.00156831 17.77798846  4.29058729  6.40314089  3.22256303  7.69722573
[229]  0.47286030  2.39938160 16.49583697  3.17460839  4.01850845  0.00000000
[235]  0.00000000  4.66281985 15.13072046 18.30148114  8.21096765  8.34397713
[241] 13.08272460  5.62327563 11.31904344  1.03085549  2.42737742 13.41734202
[247]  1.57287939 12.55610764 12.62299463  8.60077770  3.25580555  0.00000000
[253] 24.82823605  6.61599965  1.62661251  0.00000000  0.00000000  5.23345697
[259] 14.69726373 17.20803151  0.00000000  6.69152914 15.95693906 17.33074566
[265]  0.00000000  9.16600460 15.44404777  0.00000000  0.05698650  0.00000000
[271]  0.00000000 22.67249867 13.34126137  0.00000000 16.41585248  0.70978094
[277]  5.88235021 34.93133940 13.74984568  0.00000000  0.00000000  8.88324041
[283] 12.60905890 11.31802411  0.01433727  0.00000000 14.49497476  3.35766440
[289]  0.00000000 21.14774512 28.05377255  0.78045947 13.19046373  0.00000000
[295]  0.00000000  7.92613635  0.00000000  0.00000000  0.00000000  8.60297887
[301]  0.00000000  0.00000000  0.13820154  0.00000000 13.23626419 20.29013773
[307]  5.45907845 10.91509699  0.90530070 11.86347711  0.00000000  0.00000000
[313]  0.00000000  0.25535809  0.00000000  0.00000000  2.09363714  0.00000000
[319]  0.00000000  1.63213104  0.64904144  0.00000000  0.00000000</code></pre>
</div>
</div>
</section>
<section id="plotting-histogram-to-reveal-distributnio-of-presch-density" class="level2">
<h2 class="anchored" data-anchor-id="plotting-histogram-to-reveal-distributnio-of-presch-density">Plotting histogram to reveal distributnio of PreSch Density</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex01_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>Very basic histogram ## Using ggplot2 to plot publication quality histogram</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>mpsz3414, </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span> <span class="fu">as.numeric</span>(<span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span>)))<span class="sc">+</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>) <span class="sc">+</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Are pre-school even distributed in Singapore?"</span>,</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle=</span> <span class="st">"There are many planning sub-zones with a single pre-school, on the other hand, </span><span class="sc">\n</span><span class="st">there are two planning sub-zones with at least 20 pre-schools"</span>,</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">"Pre-school density (per km sq)"</span>,</span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex01_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="plotting-of-scatterplot-showing-relationship-between-pre-school-density-and-pre-school-count" class="level2">
<h2 class="anchored" data-anchor-id="plotting-of-scatterplot-showing-relationship-between-pre-school-density-and-pre-school-count">Plotting of scatterplot showing relationship between Pre-school Density and Pre-school count</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>mpsz3414, </span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">y =</span> <span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span>, </span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">x=</span> <span class="fu">as.numeric</span>(<span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span>)))<span class="sc">+</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">fill=</span><span class="st">"light blue"</span>) <span class="sc">+</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">""</span>,</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">"Pre-school density (per km sq)"</span>,</span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="st">"Pre-school count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex01_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>